language: python
python:
  - "3.6"

install: true
#  - pip install -e . --use-mirrors

before_script:
  - cd
  - git clone https://github.com/akayunov/sc2.git
  - pip install -r sc2/requirements.txt
script:
  - cd ~/sc2
  - python --version
  - pytest bin/coverage-report.py
after_success:
  - coveralls
after_failure: true